# Generated by Django 3.2.6 on 2021-11-22 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('developer', models.CharField(max_length=512)),
                ('publisher', models.CharField(max_length=512)),
                ('time_playing', models.TimeField(default='00:00:00')),
                ('status', models.CharField(choices=[('opt1', 'Ainda jogando'), ('opt2', 'Apenas Quest Principal'), ('opt3', 'Principal + alguns Extras'), ('opt4', 'Complecionista')], default='opt1', max_length=100)),
                ('owner', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
