# Generated by Django 3.2.6 on 2021-11-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('developer', models.CharField(max_length=512)),
                ('publisher', models.CharField(max_length=512)),
                ('playing', models.IntegerField(choices=[(0, 'False'), (1, 'True')])),
                ('mainquest', models.IntegerField(choices=[(0, 'False'), (1, 'True')])),
                ('mainquestPlus', models.IntegerField(choices=[(0, 'False'), (1, 'True')])),
                ('complete', models.IntegerField(choices=[(0, 'False'), (1, 'True')])),
            ],
        ),
    ]
