# Generated by Django 3.2.6 on 2021-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='game',
            name='mainquest',
        ),
        migrations.RemoveField(
            model_name='game',
            name='mainquestPlus',
        ),
        migrations.RemoveField(
            model_name='game',
            name='playing',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('opt1', 'Ainda jogando'), ('opt2', 'Apenas Quest Principal'), ('opt3', 'Principal + alguns Extras'), ('opt4', 'Complecionista')], default='opt1', max_length=100),
        ),
    ]
