# Generated by Django 3.2.6 on 2021-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.AddField(
            model_name='game',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
