# Generated by Django 3.2.6 on 2021-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20211123_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
