# Generated by Django 3.2.6 on 2021-11-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20211120_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_playing',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
