# Generated by Django 3.2.6 on 2021-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
