# Generated by Django 3.2.6 on 2021-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_path',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
