# Generated by Django 3.2.6 on 2021-11-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0005_game_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='owner_id',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.usuario'),
        ),
        
      

    ]
