# Generated by Django 3.2.6 on 2021-11-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_cover_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('opt0', 'Unlisted'), ('opt1', 'Switch'), ('opt2', 'Wii U'), ('opt3', 'Wii'), ('opt4', 'GameCube'), ('opt5', 'N64'), ('opt6', 'SNES'), ('opt7', 'NES'), ('opt8', 'GBA'), ('opt9', 'GBC'), ('opt10', 'GB'), ('opt11', 'PS1'), ('opt12', 'PS2'), ('opt13', 'PS3'), ('opt14', 'PS4'), ('opt15', 'PS5'), ('opt16', 'Xbox'), ('opt17', 'Xbox 360'), ('opt18', 'Xbox One'), ('opt19', 'Xbox Series'), ('opt20', 'PC')], default='opt0', max_length=15),
        ),
    ]
