# Generated by Django 3.2.6 on 2021-11-27 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_completion',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
