# Generated by Django 3.2.6 on 2021-11-27 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_path',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, choices=[('opt0', 'Unlisted'), ('opt1', 'Switch'), ('opt2', 'Wii U'), ('opt3', 'Wii'), ('opt4', 'GameCube'), ('opt5', 'N64'), ('opt6', 'SNES'), ('opt7', 'NES'), ('opt8', 'GBA'), ('opt9', 'GBC'), ('opt10', 'GB'), ('opt11', 'PS1'), ('opt12', 'PS2'), ('opt13', 'PS3'), ('opt14', 'PS4'), ('opt15', 'PS5'), ('opt16', 'Xbox'), ('opt17', 'Xbox 360'), ('opt18', 'Xbox One'), ('opt19', 'Xbox Series'), ('opt20', 'PSP'), ('opt21', 'PSVita'), ('opt22', 'NDS'), ('opt23', '3DS'), ('opt24', 'New3DS'), ('opt25', 'Atari 2600'), ('opt26', 'Apple ]['), ('opt27', 'PC')], default='opt0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('opt1', 'Ainda jogando'), ('opt2', 'Apenas Quest Principal'), ('opt3', 'Principal + alguns Extras'), ('opt4', 'Complecionista')], default='opt1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_completion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_playing',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
