# Generated by Django 3.2.6 on 2021-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211123_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
