# Generated by Django 3.2.6 on 2021-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211123_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio_id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
