# Generated by Django 3.2.6 on 2021-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_bio_bio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
